apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config              # Name of the ConfigMap
data:
  Course: AWS DevOps              # Key-value pair: Course name
  Trainer: Madhu Kiran            # Key-value pair: Trainer's name
  Institute: Mind Circuit Pvt ltd # Key-value pair: Institute name



#kubectl apply -f configmap.yaml
#kubectl get cm -> Lists ConfigMaps
#kubectl decsribe cm nginx-config